%YAML 1.1
---
version: 1
algorithms:
  - BlackLevel:
  - Awb:
  - Ccm:
      ccms:
        - ct: 5000
          ccm: [ 1.6680, -0.6047, -0.0633,
                -0.4641, 1.6539, -0.1899,
                -0.0633, -0.7242, 1.7875 ]
  - Adjust:
  - Agc:
...
